var found = true;
var grade = 88.6;
var firstName = 'Anup';
var lastName = 'Eric';
console.log(found);
console.log("The grade is " + grade);
console.log("Hi ".concat(firstName, " ").concat(lastName));
var anyVar = 1;
anyVar = "Ammy";
console.log(anyVar);
